### ISSUE TITLE
Data/Shops is used instead of Data/AudioChanges

### ISSUE THREAD

**Issue by cpulley** [AnotherPillow/CM2CP#1]
I don't have a lot of experience with SMAPI / CP, so there might be a good reason for this, but from [this documentation](https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#Custom_audio) it seems like CM2CP should use Data/AudioChanges by default. At the very least, I can say that change was needed for converting Piano Valley.

Regardless, thanks for your work!

**Comment by AnotherPillow** [comment]
> I don't have a lot of experience with SMAPI / CP, so there might be a good reason for this, but from [this documentation](https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#Custom_audio) it seems like CM2CP should use Data/AudioChanges by default. At the very least, I can say that change was needed for converting Piano Valley.
> 
> Regardless, thanks for your work!

Ah, thank you! Copied the code from STF2CP and didn't fully test it.
