### ISSUE TITLE
Content with missing attributes

### ISSUE THREAD

**Issue by emurphy42** [AnotherPillow/CM2CP#2]
I had to change a couple lines in Converter.py to avoid some KeyError issues:

                    'Category': 'Ambient' if track.get('Ambient') == True else 'Default',
                    'Looped': track.get('Loop') if track.get('Loop') else False

(Sorry, I don't know git well enough to do this as a pull request)

**Comment by AnotherPillow** [comment]
Done. Added you as co-author to the commit too.
